networks:
    test:
        external: ENC[AES256_GCM,data:Erxmxg==,iv:Aj937zSeHdclam8MuvxrLXAdsZVM13nJvU0PcLSPvaE=,tag:qgcR2dUNFqs3D4CMi4Docw==,type:bool]
services:
    caddy:
        extra_hosts:
            - ENC[AES256_GCM,data:t2Dj480FykJMlm1yopyMlVfWVXmgwtnp8G+A4mxTGsir,iv:MlcljcacYRXYXa69Ep8kEt35w93vEoZlC6VHYm0YIV0=,tag:WP5ZYWjXgV7gz1EtHRSjDg==,type:str]
        image: ENC[AES256_GCM,data:nxeJAohCwSSy0JxL4oMQuDVnynVnJLKfGjG+6Ndg,iv:enNM13jpE8A3Bj6AtX56vL0GD2GpU4rtYtkWQuVcMfU=,tag:s4GEB5BUGYwo9AKWK8qN4w==,type:str]
        labels:
            caddy_0: ENC[AES256_GCM,data:F+NZ4+WyHTj7+w==,iv:MtWh9IM3PqhRNvPF3VT/5OqlB2khD7S+x/gGNOZn0F8=,tag:dPXS7veT0GVYvbQXhXKz3w==,type:str]
            caddy_0.tls: ENC[AES256_GCM,data:6tUCLlp8DEdNJHWzLA==,iv:ipbO84aZ/zUFOCgKluTSFlP3SPnO9irSozzxProtcqs=,tag:7oyUx0iIrHvU30c4qbHUTw==,type:str]
            caddy_1: ENC[AES256_GCM,data:kekfMtPKNUAeug==,iv:quRoZQEhu9Hq1+6QCGXzN3qzgNQSwzJGIrkUSJKug4I=,tag:cFIxMn7C/brSpsH4JkcVtQ==,type:str]
            caddy_1.tls: ENC[AES256_GCM,data:XhLcSJpCdQAtIe3sVQ==,iv:4rIRFWr6OpSA3zLzkkOGgbSs4QFDPgaxOCY7CbYW1N8=,tag:VDv20XFS10nVGPaMztR8qA==,type:str]
            caddy_1.tls.dns: ENC[AES256_GCM,data:6ga4cbx7nJkk/Y+NO3NfxWIyAHBTRv3tc2L2N/xNYPDlb9V+Ebpkxd+EAw==,iv:9Wh0RanQ2CfzdfGbkvidoby5Xby9qHUiar+SCvnNmdY=,tag:yh7KRK49fCr5Y0bb5eZntw==,type:str]
            caddy_1.tls.resolvers: ENC[AES256_GCM,data:m+mkLlaylA==,iv:qeUZUVGj+7/EAobC4fRhf82oVfk/RGQ1TMozYvAYasc=,tag:zdB/4/b/Z+xEOMIAD2p4PA==,type:str]
        networks:
            - ENC[AES256_GCM,data:XtBbf+f2rw==,iv:q+kwe/SPVHQdFQca/oDXRLYFDzJAxBWHyPM/RYFyHbM=,tag:yR3bl8kGRAlO3y1QIGnPMw==,type:str]
            - ENC[AES256_GCM,data:numIAA==,iv:NB9ZU0CzcY4Dq+S68ogJWmV+FpqnjnFAa4cJ84nj9c8=,tag:BOOyBrzAZavv79/HIlZ3qw==,type:str]
        ports:
            - ENC[AES256_GCM,data:SMy1d5U=,iv:UrLA6AsqZSy7HWWMaR9t7p26hMaZcPTxyAqj320qbVg=,tag:vwDM7KenndtiQfuq4qcj8Q==,type:str]
            - ENC[AES256_GCM,data:hx/GtSLCdw==,iv:0kycyWkRO6e3LnDuoTFx9K1KKzkfJBxSCg9gqP/+cEA=,tag:xkgKuTz8H2QVPwdttgX/Lw==,type:str]
        restart: ENC[AES256_GCM,data:b4IymJDwpdwRuk6m5Oo=,iv:3G+OV2APvAfQ8ajxXTZSmLCJbn5BD1Fxxp0JLZbydiE=,tag:Zas87+B5EXHDKI7EiDb9vw==,type:str]
        volumes:
            - ENC[AES256_GCM,data:364EGsew88gA2N9uP2rswyEUnIGLJf6vhICARcy7NVTfH9xOE3Vbu8s=,iv:tcCq7I2SE4Qt2UmMreClXVy/jFsTHbxpqpUnJVKLrW8=,tag:SKiZcb7+58AaItGA9jsnHA==,type:str]
            - ENC[AES256_GCM,data:N0s8YqFFT9ZZ0A==,iv:lp1A9pqM9JyxXw+dM8g2nTkMU6eKQZu5/ST7q4wJS84=,tag:s9L3zSbzSstHMwDTo+rKKg==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age1qxmaf3rfgy4sezh67sg45myaal7r4l6am6xp8027nn0425k555kqjky86d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUE04aXBsNFMzR01EMG5n
            bmlPblRYanNESEZOVjVqRXJJeWpVTFoxUUNrCkRLU3o4bmxua2JMMFc5YTVpOGha
            dDhZaHo5dU5qU1FPdG9mMDQ1WS85MmcKLS0tIGdnWnNFdnZWNWdlVU5Td1lkdEpy
            RzZSVEVjL3hheFE5dDdxU2pHcytYZFEKjeMFxqXBOAM1ziEnvJDo4+i5YdVd4Yan
            mH2Ju3zRA8mRgAH0abNwBuakaK1oo9+oXF/3m6UxMQjVQjOCuZ1OMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T06:11:48Z"
    mac: ENC[AES256_GCM,data:pD/gyNGdnCH52BYQWgJxRxd0okE909vzIHL/NOutVXa8FmBGdQze0iXDUkzvTOr5DmoTY19sRtC9sTz0P/kAWkHVseWruRcF4Qb1RbV77vyIYlRwBprRtlmqVSS5Ycvr2eG//l1CqssPF/QwfxcXNRG9vkozn7/u3kSxWtgnmaA=,iv:G/ZUpoYEX13gkEqW9H+9x6kpRaTOClxpEhe2I6Fj9nM=,tag:BvqOslJRff5XNnxGWcJ8Yw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2