[[resource_sync]]
name = "komodo"

[resource_sync.config]
delete = true
git_account = "komodo"
include_user_groups = true
include_variables = true
managed = true
repo = "komodo"
resource_path = ["."]
