[[variable]]
name = "DEFAULT_EMAIL"
value = "max@excloo.com"

[[variable]]
name = "DEFAULT_ORGANIZATION" 
value = "excloo"

[[variable]]
name = "DEFAULT_TIMEZONE"
value = "Australia/Sydney"

[[variable]]
name = "DOMAIN_EXTERNAL"
value = "excloo.net"

[[variable]]
name = "DOMAIN_INTERNAL"
value = "excloo.dev"
