services:
    beszel-agent:
        environment:
            HUB_URL: ENC[AES256_GCM,data:mZjc3bXtUV+rKM4q7YvElOC6r/t2RYysT++OPZFHrKZeqXdc,iv:M2NBnjgH73oFnH5mPcj/6iaVbIivQLXfdMcdGTCFQw4=,tag:eDCqMSRzuQ82eFicPN6BQQ==,type:str]
            KEY: ENC[AES256_GCM,data:M6GPngUHofSiXj5BLj7n3R9mzyarlPgNUK9s7cUh8SYGQ+CuH7rFQ2yllAo71vGKnCTAYpSJn2lpfHNfHe0H+Do5NzrIG1QfPXLh8afwYz0=,iv:8zOmU7tL1RVijDIrvIN4GLxj5Wq5RbaZS4RFIavpyBw=,tag:44G+UM2ExZ992SG3H2S3/w==,type:str]
            LISTEN: ENC[AES256_GCM,data:TdclYq4=,iv:k3RUJfJDcoiV6ueJsqtDfm4MlK9w9/mKRAXuaLPbwvw=,tag:kDSPrhN0v1J0DpzU/0AwvA==,type:int]
            TOKEN: ENC[AES256_GCM,data:7ud4UzrWgWWdCMUeqMMLaWy+u6t2mVAKaumLupO1udnxgVD9,iv:SwKQC3JP4MlMWK9kha/R3/nUiW1VT1Q7p/GX18Z9iRY=,tag:9SQR17olmLj9jKK6kHRW/A==,type:str]
        image: ENC[AES256_GCM,data:04/al9++cKFCK0r55iWVpdnwwLpKHUBDJdCh,iv:QPYpgEA+ZlTORYXsGLfJddKetH/5TCoyYyud4DqeLAg=,tag:iLxTZJfGt8IPzJXWqXHBtg==,type:str]
        network_mode: ENC[AES256_GCM,data:fjcC3A==,iv:EPItYzXKFSPj4BEM0dRC4Wk2R8S/1JZJ4OcNQ0qKrHo=,tag:dxMhvjU5ihIUd/vIjgDiEw==,type:str]
        restart: ENC[AES256_GCM,data:z0tPiAxosnC55//ueZo=,iv:rtUn4hexRoYq7PzD8tgpF6gpoboQK7zoQ9Z692hnwt4=,tag:B1J8jvlujObtSfsrHxo7dQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:KvLQo/FE5/ZmeGlX+JXjKu9O2XYQhaLONyhLGOJxUi5icpkXnBqfKFoA2vVXK/4bOYy1E6rBJUFCLJyEy2TM8pcZ,iv:arlAHdmj2/Srfttf/VBIFpv/IzORnb247sHu0vzLC1Q=,tag:tDhnuNmzRO93NvG+a/qn6g==,type:str]
            - ENC[AES256_GCM,data:cucO2rENQAQ0UCvPipfzKQelIsLXin1Yinlt8+4jh4zGLUafjoMqQ6IRDtk=,iv:XYC5wjRpj0XsbVsEvWKPVNSDe6OWCTfZ6h67DZkBmSI=,tag:WrKJfZ6Iy5UEZvBK7nJKKw==,type:str]
            - ENC[AES256_GCM,data:eICKZp64sKs1XSSXbMNbX+oc6k/PXYeIsgw=,iv:8bMeUZ1r21iaycTcAJqMm5stKU2ShojEVKvtsSKHSfw=,tag:lzU6p5TcKI0gADy5fLCfZA==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVkpoK1VDcC9vMVgzWXZO
            c3FUTCtScEMzR3VBNlRkUWtZODFUMDJpNERvClJTVlFycmxDU0pwdXJHbXNCV0JL
            N0xtWlhuQi9YYzV6alhiYUgrWWVmQk0KLS0tIHAwYitLUWJ6U3lGS1l5eGFuVG5y
            VkVGWWhUek5GbEQyYXcwUUFOalZxbzAKqWAjz2AmwrMFD2OcOyWgfh6TrSMI4xO9
            ewoRsFungkeY34BD0lqXA/4RQuHAi7lSlPGFlwOiKgT7YLRf6qs2/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T23:02:10Z"
    mac: ENC[AES256_GCM,data:zsXsevA9VMoFCfqh9ai/eYAZL1Ams9C6niwZ7kLTngjsOZCu441UkVZsDXO6rX4VyqHMa87RX8wBRXWJgTmG7FQmmhMZKbyynomK16SJfD2Tpmq92ecRjFpXlGwmXv9ntfUMcnvzW9LXrTCy5KwYrFPixqxmm2bvzonajrzH7Uk=,iv:/JZcKt1+pJL+I6wHbBqnW9XHxgG4VEHfnuH1qJyyWW0=,tag:sD4SEqKhQGk+F5nxl4HjbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
