networks:
    test:
        external: ENC[AES256_GCM,data:wrcU/A==,iv:tIKsw+iqK/8NeS+u9KExqWKO51B3zHU3MNA1ZpnuFWA=,tag:m8c0Oj8/9Er0cV4gcj7DYg==,type:bool]
services:
    caddy:
        extra_hosts:
            - ENC[AES256_GCM,data:fTEo9OmFyTWErhR6l58I9Y8eTT5B045InkwozCRFGd1j,iv:T9lNgxJylHmsEPkaSU4bmTOYmI6va+NYxM2EFTIaCBo=,tag:p56k5wb/o4TXIcTb6Tvb2A==,type:str]
        image: ENC[AES256_GCM,data:O7C+yzFmzaNXU4aErFUibBnWsM/qLxuwlv4ppMUi,iv:XNTE2xXKNoUJYgBeBX0HRPFMy54z9CS3n3HpLzZPUCE=,tag:T0Np9YGZMs3kZ850O8CudA==,type:str]
        labels:
            caddy_0: ENC[AES256_GCM,data:qRNckLIhv2YG+A==,iv:eGXAdqO/Wb4lwtfEngSFvnj5y1+LVQEoT+cAyyJcXeE=,tag:Ge2t3LAzxU352SZ1Vitr3Q==,type:str]
            caddy_0.tls: ENC[AES256_GCM,data:VbUb5Lo48zTP2HriXw==,iv:QCnXAwgXP1qV7X7irGOD1dT7PykKUfgQCdIl84n7OJQ=,tag:dPs6H3l0MJmBRJ/B7GJjag==,type:str]
            caddy_1: ENC[AES256_GCM,data:C5jbsA4zookOiA==,iv:NHcg6eevyORFF0ORObLct9dv2qimSQc3AHzpUNewyJ4=,tag:vfp1aAkYZwyPhmA7PVubpA==,type:str]
            caddy_1.tls: ENC[AES256_GCM,data:X1HblKph0z4GkeJO0A==,iv:v2ojgpcNYGkAGGvTKtOjHNHs5YrZR4RRle3sm2hg1ck=,tag:5rcLCmk2hP7/yE9A3LgRDA==,type:str]
            caddy_1.tls.dns: ENC[AES256_GCM,data:MlMp1OoXpfd4Omu7fGEM5zIC8hWIYyjnHlSjpVPdvo3fXFI/w650dBQrGA==,iv:khKAPE1asJGh8iDmwsKJRjS3IKIx7+vTUyRQlXZx16w=,tag:xURKDayzLZIQkjFOJnHkEQ==,type:str]
            caddy_1.tls.resolvers: ENC[AES256_GCM,data:dPajfUzVYw==,iv:ZrJMKGhPNms8jE3lFVl2KppUCBO5U4vLycOD3xJFkv8=,tag:GhLCx4g6mpy4Q6CXYhN8dQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:lGSXFQnD+A==,iv:llcBlxRVC1Gk3xrXesSLkgT/ndX/y7+LyzZiAoit8mU=,tag:fQp/R26XXETawuerlt/N1Q==,type:str]
            - ENC[AES256_GCM,data:epbj4A==,iv:SiwM/TEQGuoTrnIxm5wH8dbn8bYYGL2jwKcn7Cmq6SE=,tag:5HEblvl7RwxjS69B7rxs+Q==,type:str]
        ports:
            - ENC[AES256_GCM,data:83oJkVs=,iv:VqaxDpWPdJs+YnPHwaP6EI4Q+9d0k/KuCnMduUZmqgA=,tag:WMASvocPG9chDNCLhYDUNw==,type:str]
            - ENC[AES256_GCM,data:+Wfwb/Xzdw==,iv:7WREokqE8jUZQCQWmHRVFEPlXPQ69k39pu1XAQfPVOY=,tag:n9D29QQzeAhr42q7Kxdqcw==,type:str]
        restart: ENC[AES256_GCM,data:3XKhLmZb8QLV5wC/vcc=,iv:BTpuSS53ReEGHmdInJh8PHP2hy6xveifObXTI4BfqUA=,tag:IQDZNQxja3R97HAype0ERw==,type:str]
        volumes:
            - ENC[AES256_GCM,data:tN7VZ4O1FrBIxXMuycy3a5GTY45vmgJL3nzX8i6ygvaPc0Azh4n+U5c=,iv:nAu4CRCnhlQ6EmJyTg8QlOtzlvzziASaswYwdVRCrQI=,tag:mcjuTVe2sHkhL6JEAlRHlw==,type:str]
            - ENC[AES256_GCM,data:3+AYtGlljhBcVQ==,iv:CF2A+zCKVntFq0vfN/+kuAYjRHuR84819T128F/ewrM=,tag:k0ZLqEgRg1WLuz5uTV8bZQ==,type:str]
volumes:
    data: null
sops:
    age:
        - recipient: age12l6yrect27n8da6f6qd3w0vlssyy9egpchnd5j5ev6hrazg0du2q07a08c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TmZiNmRnRUwyMTZVbmtB
            Wi9vM0JPbzBoQXZweTBPajd5VGdKdXlxTVRRCnBSakR2VVhMR1oxckkrQlNEWndl
            eCtuMFVGUUoyMzNTMkJQMXo0aFkra1EKLS0tIEhLVExKVTljVFVFUzZreHFiSnhC
            M01sR2JEa2ppd1prYk5yclNNVFpuTzQKm/DpCwuYGWBUufRmfiPe+i9ZEa+lXv1R
            oTfuvILfB2cqt5ROg21al9bFsWbQpdKhScsPRh4RghWFgqc4RZF93Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T06:11:48Z"
    mac: ENC[AES256_GCM,data:6Q33LAnTAtyVdQmgxvc1mwZJeW9kNs2IaYPdzitHWrkGjjxqc24RotKX2iWMddQyFIhKtyhOyMXE+0u0zNwoUX7CNrGKsnRBYxbMxblnUWwThu97uEEUXrvv7PgnSWptHro3sKrTZkZD9/NWqR1YqMJJHYLV8obHtrJQvwN/Alo=,iv:bzd/b+Cwo3eFlJ9FNHkzpdHyKwgWtLJpgDkv1MAO87E=,tag:88P2J/G+PlNH5Mr7Z57A+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2